apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing-2
  template:
    metadata:
      labels:
        app: testing-2
    spec:
      containers:
        - name: testing-2
          image: nginx
          ports:
            - containerPort: 80